Simplemooc/accounts/urls.py
import django.contrib.auth.urls
from django.urls import path,include
from django.contrib.auth import views as auth_views

app_name = 'Accounts'

# urlpatterns = [
#     #path('entrar', auth_views.LoginView.as_view()),
#     path(r'^entrar/$', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='accounts'),
#
#     #path('entrar/',login.as_view(template_name="accounts/login.html", name="login")),
# ]


#Add Django site authentication urls (for login, logout, password management)
urlpatterns = [
    path('entrar/', include('django.contrib.auth.urls'),name='login'),
]

Simplemooc/core/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'Simplemooc'
urlpatterns = [
    path(r'',views.home, name='home'),
    path(r'contato/',views.contacts, name='contato'),
]

Simplemooc/courses/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from . import views

app_name = 'Courses'
urlpatterns = [
    path(r'',views.index, name='index'),
    #re_path(r'^(?P<pk>\d+)/$', views.details, name='details')
    re_path(r'^(?P<slug>[\w_-]+)/$', views.details, name='details')
]

Simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Simplemooc.core import views
admin.autodiscover()

urlpatterns = [
    #path(r'', views.home, name='home'),
    #path(r'contato/',views.contacts, name='contato'),
    path(r'', include('Simplemooc.core.urls',namespace='Simplemooc')),
    path(r'cursos/',include('Simplemooc.courses.urls',namespace='Courses')),
    path(r'conta/',include('Simplemooc.accounts.urls',namespace='Accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Simplemooc/accounts/models.py
from django.db import models

# Create your models here.

Simplemooc/courses/models.py
from django.db import models

class CoursesManager(models.Model):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | models.Q(description__icontains=query)
        )

class Courses(models.Model):
    name = models.CharField('Nome',max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição',blank=True)
    about = models.TextField('Sobre o Curso',blank=True)
    start_date = models.DateField('Data Ínicio', null=True, blank=True)
    image = models.ImageField(upload_to='courses/images', verbose_name='Imagem',null=True,blank=True)
    created_at = models.DateTimeField('Criado em',auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em',auto_now=True)


    object = CoursesManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return (self.slug)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']

Simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Já existe usuário com este E-mail')
        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

Simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from Simplemooc.core.mail import send_mail_template

class ContactCourse(forms.Form):
    name = forms.CharField(label='Nome',max_length=100)
    email = forms.EmailField(label='Email')
    message = forms.CharField(label='Mensagem/Dúvidas',widget=forms.Textarea)

    def send_mail(self, course):
        subject = '[%s] Contato' % course
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'courses/contact_email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]
        )

Simplemooc/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.conf import settings

from .forms import RegisterForm

def accounts(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('Simplemooc:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

def passar()
pass

Simplemooc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'home.html')

def contacts(request):
    return render(request,'contact.html')

Simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404
from .models import Courses
from .forms import ContactCourse

def index(request):
    courses = Courses.objects.all()
    template_name = 'courses/index.html'
    context = {'courses':courses}

    return render(request,template_name,context)

# def details(request, pk):
#     course = get_object_or_404(Courses,pk=pk)
#     template_name = 'courses/details.html'
#     context = {'courses':course}
#
#     return render(request,template_name,context)

def details(request, slug):
    course = get_object_or_404(Courses, slug=slug)
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course)
            form = ContactCourse()
    else:
        form = ContactCourse()

    context['form'] = form
    context['course'] = course
    template_name = 'courses/details.html'
    context = {'courses':course, 'form':form}

    return render(request, template_name, context)

Simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

Simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

Simplemooc/core/templates/base.html
<!doctype html>
{% load static%}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}" />
</head>
<body>
  <div class="header">
      <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
          <a class="pure-menu-heading" href="{% url 'Simplemooc:home' %}">SIMPLE MOOC</a>
          <ul>
              <li class="pure-menu-selected"><a href="{% url 'Simplemooc:home' %}">Início</a></li>
              <li><a href="{% url 'Courses:index' %}">Cursos</a></li>
              <li><a href="{% url 'Accounts:details' %}">Contato</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'Accounts:logout' %}">Sair</a></li>
              {% else %}
              <li><a href="{% url 'Accounts:login' %}">Entrar</a></li>
              {% endif %}
          </ul>
      </div>
  </div>
<div class="content">
{% block content %} {% endblock %}
    <div class="footer">
        Plataforma de Ensino Online -  Criado Por Diego Gomes
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

Simplemooc/core/templates/contact.html
{% extends "base.html" %}
{% block content %}
<div class="content">
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1>Fale conosco</h1>
            <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
            <h4>Links</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
                <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
            </ul>
        </div>
    </div>
  {% endblock %}

Simplemooc/core/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h2 class="splash-subhead">
                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}    

Simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

Simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ courses }}
                </h1>
                <h2 class="splash-subhead">
                    {{ courses.description }}
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ courses.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if courses.image %}
            <img src="{{ courses.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/dafault_img_400x250.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="POST">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

Simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="pure-g-r content-ribbon">
  <div class="pure-u-1">
    <div class="l-box">
      <h4 class="content-subhead">Lista de Cursos Disponiveis</h4>
      <p>Lista de cursos Disponiveis no momento:</p>
    </div>
  </div>
</div>
{% for curso in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
          <a href="{{curso.get_absolute_url}}">
            {% if curso.image %}
            <img src="{{curso.image.url}}" alt="{{curso.name}}" />
            {% else %}
            <img src="{% static 'img/default_img_400x250.png' %}" alt="{{curso.name}}" />
            {% endif %}
          </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
          <a href="{{curso.get_absolute_url}}">
            <h4 class="content-subhead">{{curso.name}}</h4>
          </a>
            <h3>Inicio em: {{curso.start_date}}</h3>
            {{curso.description|linebreaks}}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
  <div class="pure-u-1">
    <div class="l-box">
      <p>Neste momento Não temos curso em Andamento</p>
    </div>
  </div>
</div>
{% endfor%}
{% endblock %}